name: IP Checker

on:
  workflow_dispatch:
    inputs:
      single_ip:
        description: "Single IP address to check (optional)"
        required: false
        type: string
      ip_file:
        description: "File with multiple IPs (optional)"
        required: false
        type: string
      upload_artifact:
        description: "Upload IP database as artifact? (true/false)"
        required: false
        default: false
        type: boolean

jobs:
  ip-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Run IP Checker
        id: run_checker
        run: |
          # Handle both input types
          if [ -n "${{ inputs.single_ip }}" ] && [ -n "${{ inputs.ip_file }}" ]; then
            python ip_checker.py --ip "${{ inputs.single_ip }}" --file "${{ inputs.ip_file }}"
          elif [ -n "${{ inputs.single_ip }}" ]; then
            python ip_checker.py --ip "${{ inputs.single_ip }}"
          elif [ -n "${{ inputs.ip_file }}" ]; then
            python ip_checker.py --file "${{ inputs.ip_file }}"
          else
            echo "Error: Please provide at least one IP input method"
            exit 1
          fi
          
      - name: Archive Report
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: ip-check-results-${{ github.run_id }}
          path: |
            ip_data/**/*.txt
